server:
  port:8090
  servlet:
    context-path: /app/api

#H2 Configurations
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:user-service;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#Actuator Configurations

